FROM apache/airflow:2.9.1-python3.11

USER root
# Cài đặt lệnh Docker CLI vào hệ điều hành của Airflow
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir pandas faker requests python-dotenv